### ISSUE TITLE
translation missing=fr.risk_menu

### ISSUE THREAD

**Issue by jbpotokar** [rolesoftware/redrisk#1] opened 2015-03-12 18:15 UTC
Hi, 

Thanks for this plugin, could be usefull. 
I've been trying to install, but first, I had to do rake redmine:plugins:migrate RAILS_ENV=production to have rake working. 
And now I have translation missing:fr.risk_menu on the main menu. Can you tell what I did wrong ? 

Regards

**Comment by bsban** [comment] 2015-03-16 04:50
try copy any other's 'fr.yml' file in config/locales.
if you need edit the file.

**Comment by leticiamara** [comment] 2015-03-17 00:15
Hi, 

This problem probably is a translation error because we do not have the file with translations to French, but even so, the Redmine should be taking the default translation that is English. We try to reproduce the error but we could not. Could you send us more information about the problem?

Thanks for use the plugin.

Regards

**Comment by rodrigogirao** [comment] 2015-06-26 00:12
Fixed in commit 02ace72
Please update to version 1.0.1

Regards,

**Closed as completed by rodrigogirao** 2015-06-26 00:12 UTC
